" Enable vim-latex
filetype plugin on
filetype indent on
syntax enable

" Set up LaTeX-specific settings
let g:tex_flavor='latex'
let g:Tex_DefaultTargetFormat = 'pdf'
let g:Tex_CompileRule_pdf = 'pdflatex -interaction=nonstopmode -synctex=1 %'

